# Generated by Django 4.0.10 on 2023-02-27 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('product_number', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
